name: Build, test and Deploy Vite Project

on:
  # Triggers the workflow on push or pull request events to the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Cache dependencies to speed up subsequent installs
      - name: Cache Node.js dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: yarn-cache-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-cache-

      - name: Install dependencies
        run: yarn install
      - name: Print secrents and variables
        run: |
          echo "VITE_APP_SECRET variable : $secrets.VITE_APP_SECRET"
          echo "VITE_APP_ENV variable : $vars.VITE_APP_ENV"

      - name: Build Vite project
        run: yarn build
        env:
          VITE_APP_SECRET: ${{ secrets.VITE_APP_SECRET }}
          VITE_APP_ENV: ${{ vars.VITE_APP_ENV }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vite-app-build
          path: ./dist

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test

  deploy:
    needs: [build, test]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Download build artifacts from the build job
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: vite-app-build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Use GitHub's automatic token
          publish_dir: .
